Repository jameshughes89/cs101, pull requests merged in 2021-07, with the labels that each got.

#26 :robot: Setup action for auto build & deploy
  .github/workflows/sphinx-build.yml
Labels: deployment --- robot :robot:

#20 Update headings
  .DS_Store
  source/gettingset.rst
  source/index.rst
  source/lab1.rst
  source/lab10.rst
  source/lab11.rst
  source/lab12.rst
  source/lab2.rst
  source/lab3.rst
  source/lab4.rst
  source/lab5.rst
  source/lab6.rst
  source/lab7.rst
  source/lab8.rst
  source/lab9.rst
  source/topic1.rst
  source/topic10.rst
  source/topic11.rst
  source/topic11b.rst
  source/topic12.rst
  source/topic13.rst
  source/topic13b.rst
  source/topic14.rst
  source/topic15.rst
  source/topic16.rst
  source/topic17.rst
  source/topic18.rst
  source/topic19.rst
  source/topic2.rst
  source/topic3.rst
  source/topic4.rst
  source/topic5.rst
  source/topic5b.rst
  source/topic6.rst
  source/topic7.rst
  source/topic8.rst
  source/topic8b.rst
  source/topic9.rst
Labels: content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#25 :mortar_board: Topic1 Review and update
  source/topic1.rst
Labels: consistency --- telescope :telescope:, content --- mortar_board :mortar_board:, formatting --- lipstick :lipstick:

#32 :art: Remove excess memes v2
  img/DL.jpeg
  img/Rubber_Duck.jpg
  img/babyKeys.jpg
  img/enthusiasm.jpg
  img/finally.jpg
  img/machine.jpeg
  img/marge.png
  img/money.jpg
  img/monster.jpeg
  img/scared.jpeg
  img/spinning.gif
  img/stackOverflow.jpg
  img/turnUp.jpg
  source/topic11.rst
  source/topic11b.rst
  source/topic13.rst
  source/topic17.rst
  source/topic19.rst
  source/topic2.rst
  source/topic4.rst
  source/topic5b.rst
  source/topic6.rst
  source/topic8.rst
Labels: art :art:
