Repository jameshughes89/cs101, pull requests merged in 2021-11, with the labels that each got.

#95 :bug: :lipstick: Unindent function call
  source/topic11.rst
Labels: formatting --- lipstick :lipstick:, typo/bug :bug:

#96 :bug: Topic12 Fix airport csv download link
  data/airports.csv
  source/topic12.rst
Labels: typo/bug :bug:

#98 :bug: Spyder spelled wrong
  source/topic13.rst
Labels: typo/bug :bug:

#100 :mortar_board: Assignment 4 Update due date and title
  source/asn4.rst
Labels: content --- mortar_board :mortar_board:

#101 :bug: Topic13b Remove extra '-'
  source/topic13b.rst
Labels: typo/bug :bug:

#102 :telescope: Lab10 Follow Conventions Better
  source/lab10.rst
Labels: consistency --- telescope :telescope:

#105 :bug: Lab11 Fix broken links to text files
  source/lab11.rst
Labels: typo/bug :bug:
