Repository jameshughes89/cs101, pull requests merged in 2022-11, with the labels that each got.

#498 :lipstick: Assignment 4 --- Rename :microscope:
  site/assignments/country-catalogue/continent.txt
  site/assignments/country-catalogue/country-catalogue.rst
  site/assignments/country-catalogue/country.txt
  site/assignments/country-catalogue/main.py
  site/assignments/country-catalogue/output.txt
  site/assignments/country-catalogue/world.png
  site/index.rst
Labels: formatting --- lipstick :lipstick:

#493 :lipstick: Assignments --- Change verbatim bits to code block
  site/assignments/starbucks/starbucks.rst
  site/assignments/tic-tac-toe/tic-tac-toe.rst
  site/assignments/zombies/zombies.rst
Labels: formatting --- lipstick :lipstick:

#494 :lipstick: Assignments --- Fix typesetting of points :microscope:
  site/assignments/starbucks/starbucks.rst
  site/assignments/tic-tac-toe/tic-tac-toe.rst
  site/assignments/zombies/zombies.rst
Labels: formatting --- lipstick :lipstick:

#499 :lipstick: Country Catalogue Assignment --- Structure
  site/assignments/country-catalogue/country-catalogue.rst
Labels: formatting --- lipstick :lipstick:

#501 🐛 💄 References Lab --- Fix numbering and add note for clarity
  site/labs/lists/references.rst
Labels: formatting --- lipstick :lipstick:, typo/bug :bug:

#503 :telescope: Objects III --- Add more imports to math
  site/topics/objects/interacting-objects.rst
Labels: consistency --- telescope :telescope:

#504 :bomb: Objects III --- Remove mention of removed methods
  site/topics/objects/interacting-objects.rst
  src/point3d.py
Labels: delete --- bomb :bomb:

#505 :lipstick: Tic-Tac-Toe Assignment --- Reorder rendering functions
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: formatting --- lipstick :lipstick:

#506 :mortar_board: Country Catalogue Assignment --- Discuss task, files, and uploading
  site/assignments/country-catalogue/country-catalogue.rst
  site/assignments/country-catalogue/world.png
Labels: content --- mortar_board :mortar_board:

#508 :mortar_board: Country Catalogue Assignment --- add get item method to section title :microscope:
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#509 :mortar_board: Country Catalogue Assignment --- `CountryCatalogue` intro and constructor
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#510 :mortar_board: Country Catalogue Assignment --- `_find` and `contains` methods in `CountryCatalogue`
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#511 :mortar_board: Country Catalogue Assignment --- `add` and `remove` methods in `CountryCatalogue`
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#512 :mortar_board: Country Catalogue Assignment --- large/small linear searches
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#513 :mortar_board: Country Catalogue Assignment --- filter method
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#515 :mortar_board: Country Catalogue Assignment --- Mention unit tests
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#514 :mortar_board: Country Catalogue Assignment --- Most populated continent
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#517 :lipstick: Country Catalogue Assignment --- Mention that the attribute should start with underscore :microscope:
  site/assignments/country-catalogue/country-catalogue.rst
Labels: formatting --- lipstick :lipstick:

#516 :mortar_board: Country Catalogue Assignment --- Discuss required magic methods
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#518 :mortar_board: Country Catalogue Assignment --- Explain the provided code
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#519 :mortar_board: Country Catalogue Assignment --- Add files to be downloaded
  site/assignments/country-catalogue/asn4.ipynb
  site/assignments/country-catalogue/asn4.py
  site/assignments/country-catalogue/country-catalogue.rst
  site/assignments/country-catalogue/country_data.csv
Labels: content --- mortar_board :mortar_board:

#520 :mortar_board: Country Catalogue Assignment --- Add link to index and remove old assignment description stuff
  site/assignments/country-catalogue/country-catalogue.rst
  site/index.rst
Labels: content --- mortar_board :mortar_board:

#521 :mortar_board: Country Catalogue Assignment --- What to submit
  site/assignments/country-catalogue/country-catalogue.rst
Labels: content --- mortar_board :mortar_board:

#522 :bug: :telescope: Unittest topic --- Update repr test
  site/topics/testing/unittest.rst
  test/test_sphere.py
Labels: consistency --- telescope :telescope:, typo/bug :bug:

#523 :bug: Tic-Tac-Toe Assignment --- Fix example for `apply_move` :microscope:
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: typo/bug :bug:

#525 :woman_technologist: :mortar_board: Sphere tests --- change attribute tests
  site/topics/testing/unittest.rst
  test/test_sphere.py
Labels: content --- mortar_board :mortar_board:

#524 :telescope: Unittest topic --- update point repr
  site/topics/objects/interacting-objects.rst
Labels: consistency --- telescope :telescope:

#526 :bug: Country Catalogue Assignment --- Add missing backticks :microscope:
  site/assignments/country-catalogue/country-catalogue.rst
Labels: typo/bug :bug:

#527 :mortar_board: Objects Lab --- Add unittests to a step in the lab
  site/labs/objects/objects.rst
Labels: content --- mortar_board :mortar_board:

#530 :bug: Collections Topic (Objects IV) --- Fix typo
  site/topics/objects/data-structures.rst
Labels: typo/bug :bug:

#531 :lipstick: Objects Lab --- Actually add refs, download, and clean unittests
  site/labs/objects/objects.rst
  test/test_circle.py
Labels: formatting --- lipstick :lipstick:

#533 :rotating_light: :bug: Country Catalogue Assignment --- Fix the provided code :rotating_light:
  site/assignments/country-catalogue/asn4.ipynb
  site/assignments/country-catalogue/asn4.py
  site/assignments/country-catalogue/continent.txt
  site/assignments/country-catalogue/country.txt
  site/assignments/country-catalogue/main.py
  site/assignments/country-catalogue/output.txt
Labels: content --- mortar_board :mortar_board:, typo/bug :bug:

#534 :mortar_board: Data Structures Lab --- assert tests -> unit tests
  site/labs/objects/data-structures.rst
Labels: content --- mortar_board :mortar_board:

#535 :bug: Sorting Topic --- Fix algo names in activity and typesetting
  site/topics/sorting/sorting.rst
Labels: typo/bug :bug:
