Repository jameshughes89/cs101, pull requests merged in 2022-10, with the labels that each got.

#432 :mortar_board: Assignment 2 --- `cure` and `infect`
  site/assignments/zombies/zombies.rst
Labels: content --- mortar_board :mortar_board:

#436 :bug: Lab 5 --- Fix math range typesetting :microscope:
  site/labs/loops/loops.rst
Labels: typo/bug :bug:

#437 :mortar_board: Assignment 2 --- Full simulation function
  site/assignments/zombies/zombies.rst
Labels: content --- mortar_board :mortar_board:

#438 :mortar_board: Assignment 2 --- Using the code for analysis
  site/assignments/zombies/zombies.rst
Labels: content --- mortar_board :mortar_board:

#441 :bug: Lab 5 --- Add missing `"`
  site/labs/loops/loops.rst
Labels: typo/bug :bug:

#439 :bomb: Assignment 2 --- Remove old description parts
  site/assignments/zombies/cdc.jpeg
  site/assignments/zombies/zgraph.png
  site/assignments/zombies/zhist.png
  site/assignments/zombies/zombies.rst
Labels: delete --- bomb :bomb:

#444 :bug: Strings Topic --- Fix typesetting
  site/topics/strings/strings.rst
Labels: typo/bug :bug:

#445 :bug: Loops topic --- Typo sill -> will
  site/topics/loops/loops.rst
Labels: typo/bug :bug:

#448 :bug: Lists topic --- Typo `od` -> `of`
  site/topics/lists/lists.rst
Labels: typo/bug :bug:

#449 :bomb: Linear Search Lab --- Remove prelab q4
  site/labs/linear-search/linear-search.rst
Labels: delete --- bomb :bomb:

#451 :bug: Zombies Assignment --- Update code with new `draw_world`
  site/assignments/zombies/asn2.ipynb
  site/assignments/zombies/asn2.py
Labels: typo/bug :bug:

#447 :bug: Strings Topic --- Fix wording
  site/topics/strings/strings.rst
Labels: typo/bug :bug:

#446 :bug: :telescope: Car Rental Topic --- Change the `@` to `:` in docstrings
  site/topics/car-rental/car-rental.rst
  src/car_rental_topic.py
Labels: consistency --- telescope :telescope:, typo/bug :bug:

#456 :mortar_board: Tic-Tac-Toe Assignment --- Set due date
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#455 :art: Sets Topic --- Update set difference image
  site/topics/tuples-dictionaries-sets/difference.png
Labels: art :art:

#457 :lipstick: Exceptions Topic --- Cleanup last section :microscope:
  site/topics/exceptions/exceptions.rst
Labels: formatting --- lipstick :lipstick:

#460 :bomb: Lists Lab --- Remove request for assert test
  site/labs/lists/1d-lists.rst
Labels: delete --- bomb :bomb:

#458 :mortar_board: Tic-Tac-Toe Assignment --- Task section
  site/assignments/tic-tac-toe/a3_programmer.jpg
  site/assignments/tic-tac-toe/a3_videoGame.jpg
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#461 :mortar_board: Tic-Tac-Toe --- Uploading notebook to Colab
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#459 :mortar_board: Tic-Tac-Toe Assignment --- Discuss and add provided file
  site/assignments/tic-tac-toe/asn3.ipynb
  site/assignments/tic-tac-toe/asn3.py
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#462 :mortar_board: Tic-Tac-Toe Assignment --- `setup_game` function
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#463 :mortar_board: Tic-Tac-Toe Assignment --- Setup game note 0,0 is top left :microscope:
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#467 :lipstick: Assignment FAQ --- Consolidate FAQ
  site/assignments/faq.rst
  site/assignments/starbucks/starbucks.rst
  site/assignments/zombies/zombies.rst
Labels: formatting --- lipstick :lipstick:

#468 :bug: Outline --- Fix table :microscope:
  site/outline/outline.rst
Labels: typo/bug :bug:

#465 :mortar_board: Tic-Tac-Toe Assignment --- `is_move_valid` function description
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#466 :mortar_board: Tic-Tac-Toe Assignment --- `apply_move`
  site/assignments/tic-tac-toe/deep_copy.png
  site/assignments/tic-tac-toe/shallow_copy.png
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#470 :mortar_board: Tic-Tac-Toe Assignment --- Read the assignment :microscope:
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#471 :telescope: Tic-Tac-Toe Assignment --- Update FAQ
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: consistency --- telescope :telescope:

#473 :telescope: Tic-Tac-Toe Assignment --- Comment out assert tests
  site/assignments/tic-tac-toe/asn3.ipynb
  site/assignments/tic-tac-toe/asn3.py
Labels: consistency --- telescope :telescope:

#474 :bomb: Tic-Tac-Toe Assignment --- Remove some old bits
  site/assignments/tic-tac-toe/a3_10x10.png
  site/assignments/tic-tac-toe/a3_3x3-2.png
  site/assignments/tic-tac-toe/a3_get_move.png
  site/assignments/tic-tac-toe/a3_is_move_valid.png
  site/assignments/tic-tac-toe/a3_make_move.png
  site/assignments/tic-tac-toe/a3_player.png
  site/assignments/tic-tac-toe/a3_set_up_game.png
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: delete --- bomb :bomb:

#475 :mortar_board: Tic-Tac-Toe Assignment --- Describe the winning condition checker
  site/assignments/tic-tac-toe/a3_check_row.png
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#478 :mortar_board: Tic-Tac-Toe Assignment --- Introduce render and `render_cell`
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#479 :mortar_board: Tic-Tac-Toe Assignment --- `render_row`
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#480 :mortar_board: Ric-Tac-Toe Assignment --- `render_board`
  site/assignments/tic-tac-toe/a3_game_print.png
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#482 :mortar_board: Tic-Tac-Toe Assignment --- Main game loop
  site/assignments/tic-tac-toe/tic-tac-toe.rst
Labels: content --- mortar_board :mortar_board:

#483 :new: :bomb: Tic-Tac-Toe Assignment --- Add link, but remove old bits
  site/assignments/tic-tac-toe/a3_O_win_4x4.png
  site/assignments/tic-tac-toe/a3_X_win_3x3.png
  site/assignments/tic-tac-toe/a3_enterMove.png
  site/assignments/tic-tac-toe/a3_enterMove_2.png
  site/assignments/tic-tac-toe/a3_input.png
  site/assignments/tic-tac-toe/a3_invalidMove.png
  site/assignments/tic-tac-toe/a3_needClear.png
  site/assignments/tic-tac-toe/a3_no_win_3x3.png
  site/assignments/tic-tac-toe/tic-tac-toe.rst
  site/index.rst
Labels: delete --- bomb :bomb:, enhancement/new :new:
